### ISSUE TITLE
Unable to resolve class Credentials

### ISSUE THREAD

**Issue by nieleyde** [SpirosLef/Pivotal_Cartridge#1]
I am unable to successfully complete the load cartridge build,  It always fails at the following spot,  I tried update Credentials plugin in Jenkins, but I'm still having the same issue.  I suspect I'm missing a dependency, but I have run out of troubleshooting ideas.

ERROR: startup failed:
workspace:/cartridge/jenkins/jobs/dsl/java_reference_application_jobsPivotal.groovy: 8: unable to resolve class Credentials 
 @ line 8, column 13.
   Credentials pivotalCred = (Credentials) new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL,java.util.UUID.randomUUID().toString(), "CF_Credentials", "user", "password")
               ^

workspace:/cartridge/jenkins/jobs/dsl/java_reference_application_jobsPivotal.groovy: 8: unable to resolve class Credentials 
 @ line 8, column 27.
   Credentials pivotalCred = (Credentials) new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL,java.util.UUID.randomUUID().toString(), "CF_Credentials", "user", "password")
                             ^

workspace:/cartridge/jenkins/jobs/dsl/java_reference_application_jobsPivotal.groovy: 8: unable to resolve class UsernamePasswordCredentialsImpl 
 @ line 8, column 41.
   s pivotalCred = (Credentials) new Userna
                                 ^

3 errors

Finished: FAILURE
 Help us localize this page

**Comment by kramos** [comment]
Hi Niel 
I think you need to create a security credential in Jenkins first called: CF_Credentials  
/cc @SpirosLef

**Comment by nieleyde** [comment]
I believe I have.
![image](https://cloud.githubusercontent.com/assets/1414858/21937401/564b4536-d985-11e6-8931-c0210430feb7.png)

**Comment by seaspy** [comment]
Hello Niel,

Sorry for my late response... 
May I ask you... Which action did you take first? Creating credentials under CF_Credentials ID and then you loaded the cartridge or the other way round?

Kind Regards,
Spiros

**Comment by nieleyde** [comment]
I tried creating credentials first under an arbitrary jenkins id, thinking I would be prompted later to specify the desired id to use for the cartridge.  When cartridge failed, I used the error from above as a hint to what the expected jenkins id (CF_Credentials) should be.  Then I tried running Load Cartridge script again, but it failed.  I tried again by creating a new project, but it failed too.

**Comment by seaspy** [comment]
Hello @nieleyde ,

There was made an upgrade in job dsl plugin in Jenkins so a couple of classes I was using are not existing any more in the packages I was importing... 
So in order to work please go in Jenkins global credentials and add the user name and password using CF_Credentials as the ID... Probably it is going to work the way you have already set it above... 
Thus if you have set [this](https://github.com/SpirosLef/adop-cartridge-pivotal-cloudfoundry.git) github URL in Load Cartridge job probably the only thing you have to do is just to re run Jenkins Load Cartridge job. 
Please make a try and let me know about the result... 

Kind Regards,
Spiros

**Comment by nieleyde** [comment]
Yes, that resolved this issue.  Thanks.  I had another issue that I will log separately, but I was able to run the whole thing.
